#include <stdlib.h>
#include <stdio.h>

#include "token.h"

token_T *init_token(char *value, int type)
{
    token_T *token = calloc(1, sizeof(struct token_T));
    token->value = value;
    token->type = type;
    return token;
}

char *type_to_string(int token)
{

    switch (token)
    {
    case IDENTIFIER:
        return "IDENTIFIER";
    case AUTO:
        return "AUTO";
    case BREAK:
        return "BREAK";
    case CASE:
        return "CASE";
    case CHAR:
        return "CHAR";
    case CONST:
        return "CONST";
    case CONTINUE:
        return "CONTINUE";
    case DEFAULT:
        return "DEFAULT";
    case DO:
        return "DO";
    case DOUBLE:
        return "DOUBLE";
    case ELSE:
        return "ELSE";
    case ENUM:
        return "ENUM";
    case EXTERN:
        return "EXTERN";
    case FLOAT:
        return "FLOAT";
    case FOR:
        return "FOR";
    case GOTO:
        return "GOTO";
    case IF:
        return "IF";
    case INT:
        return "INT";
    case LONG:
        return "LONG";
    case REGISTER:
        return "REGISTER";
    case RETURN:
        return "RETURN";
    case SHORT:
        return "SHORT";
    case SIGNED:
        return "SIGNED";
    case SIZEOF:
        return "SIZEOF";
    case STATIC:
        return "STATIC";
    case STRUCT:
        return "STRUCT";
    case SWITCH:
        return "SWITCH";
    case TYPEDEF:
        return "TYPEDEF";
    case UNION:
        return "UNION";
    case UNSIGNED:
        return "UNSIGNED";
    case VOID:
        return "VOID";
    case VOLATILE:
        return "VOLATILE";
    case WHILE:
        return "WHILE";
    case CONSTANT:
        return "CONSTANT";
    case STRING_LITERAL:
        return "STRING_LITERAL";
    case ELLIPSIS:
        return "ELLIPSIS";
    case RIGHT_ASSIGN:
        return "RIGHT_ASSIGN";
    case LEFT_ASSIGN:
        return "LEFT_ASSIGN";
    case ADD_ASSIGN:
        return "ADD_ASSIGN";
    case SUB_ASSIGN:
        return "SUB_ASSIGN";
    case MUL_ASSIGN:
        return "MUL_ASSIGN";
    case DIV_ASSIGN:
        return "DIV_ASSIGN";
    case MOD_ASSIGN:
        return "MOD_ASSIGN";
    case AND_ASSIGN:
        return "AND_ASSIGN";
    case XOR_ASSIGN:
        return "XOR_ASSIGN";
    case OR_ASSIGN:
        return "OR_ASSIGN";
    case RIGHT_OP:
        return "RIGHT_OP";
    case LEFT_OP:
        return "LEFT_OP";
    case INC_OP:
        return "INC_OP";
    case DEC_OP:
        return "DEC_OP";
    case PTR_OP:
        return "PTR_OP";
    case AND_OP:
        return "AND_OP";
    case OR_OP:
        return "OR_OP";
    case LE_OP:
        return "LE_OP";
    case GE_OP:
        return "GE_OP";
    case EQ_OP:
        return "EQ_OP";
    case NE_OP:
        return "NE_OP";
    case SEMICOLON:
        return "SEMICOLON";
    case L_BRACE:
        return "L_BRACE";
    case R_BRACE:
        return "R_BRACE";
    case COMMA:
        return "COMMA";
    case COLON:
        return "COLON";
    case EQUALS:
        return "EQUALS";
    case L_PARENTHESIS:
        return "L_PARENTHESIS";
    case R_PARENTHESIS:
        return "R_PARENTHESIS";
    case L_BRACKET:
        return "L_BRACKET";
    case R_BRACKET:
        return "R_BRACKET";
    case PERIOD:
        return "PERIOD";
    case AMPERSAND:
        return "AMPERSAND";
    case EXCLAMATION_MARK:
        return "EXCLAMATION_MARK";
    case TILDE:
        return "TILDE";
    case MINUS:
        return "MINUS";
    case PLUS:
        return "PLUS";
    case MULTIPLY:
        return "MULTIPLY";
    case DIVIDE:
        return "DIVIDE";
    case PERCENT:
        return "PERCENT";
    case LESS_THAN:
        return "LESS_THAN";
    case GREATER_THAN:
        return "GREATER_THAN";
    case CARET:
        return "CARET";
    case VERTICAL_BAR:
        return "VERTICAL_BAR";
    case QUESTION_MARK:
        return "QUESTION_MARK";
    case END_OF_FILE:
        return "END_OF_FILE";
    default:
        return "TOKEN_NOT_VALID";
    }
}